# -*- coding: utf-8 -*-
"""attack_dense_rev.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PJDuvkYvaq6VGAXcA4mn3oq7niblhP9g

## IoT Network Attack Classification

This project uses a network traffic dataset sourced from **Kaggle** to analyze and classify IoT network attacks using machine learning.

The workflow covers data cleaning and preprocessing (ETL), exploratory data analysis, and multi-class classification using both a deep neural network (TensorFlow/Keras) and a Random Forest classifier (Scikit-learn), with the two approaches compared on classification accuracy.

---

### Imports
"""

import os
import math
from scipy.stats import randint

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np


from tensorflow import keras
from tensorflow.keras import layers

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.ensemble import  RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score

"""---

### Data Importing

We use the `pandas` library to load the dataset from a Parquet file into a DataFrame.
"""

data=pd.read_parquet('data_file_0.parquet')

"""---

### Exploratory Data Analysis

Since the dataset represents IoT network traffic, we expect substantial variation across features and a considerable number of outliers. To characterize the data before modeling, we perform a descriptive analysis using `pandas` and `numpy`, focusing on the following:
- Outlier detection
- Visualization
- Distribution analysis
- Correlation analysis
"""

data.columns

data.select_dtypes(include=[np.number]).skew()

cols = data.select_dtypes(include='number').columns

n_cols = 2                          # Number of plots per row
n_rows = math.ceil(len(cols) / n_cols)

fig, axes = plt.subplots(
    n_rows,
    n_cols,
    figsize=(8 * n_cols, 6 * n_rows)
)

axes = axes.flatten()

for i, col in enumerate(cols):
    sns.boxplot(
        data=data,
        x='Attack_type',
        y=col,
        hue='Attack_type',
        palette='Set2',
        legend=False,
        ax=axes[i]
    )

    axes[i].set_title(col)
    axes[i].set_xlabel("")
    axes[i].tick_params(axis='x', rotation=45)

# Remove any unused subplots
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

"""> The boxplots reveal that many columns contain distinct outlying values for each attack type, which suggests these features could serve as a basis for segmentation. Additionally, the specific columns exhibiting outliers vary by attack type, indicating that different attacks produce different patterns of network behavior.

#### Correlation Analysis

Next, we examine pairwise correlations among the numeric features to identify redundancy and relationships that may influence model selection.
"""

corr_d=data.drop(['Attack_type','Column1','id.orig_p','id.resp_p']+[x for x in data.select_dtypes(exclude=np.number).columns],axis=1)
corr_matrix=corr_d.corr()[corr_d.corr()>0.5].fillna('<0.5')
corr_matrix

"""> The correlation matrix shows strong correlations (> 0.5) between several feature pairs, which is an important consideration when selecting and preprocessing a model.

---

### Model Selection

Given the large number of outliers and the strong correlations present in the data, models such as SVC and Logistic Regression would require extensive scaling and preprocessing to perform well. We instead select two models that are more robust to these characteristics: a **Random Forest Classifier**, which is largely insensitive to feature scale and correlation, and a **Dense Neural Network**, which can learn complex non-linear relationships directly from the data.

---

### Data Preparation

Before modeling, we prepare the dataset by separating features from the target label, encoding categorical variables, scaling numerical features, and splitting the data into training and validation sets.
"""

# creating x,y label dataset

y_label=data['Attack_type']
x_label=data.drop(['Attack_type','Column1','id.orig_p','id.resp_p'],axis=1)

x_label.dtypes

"""#### Encoding and Scaling

We encode the target labels as integers and build a `ColumnTransformer` that one-hot encodes categorical features and standard-scales numerical features, ensuring all inputs are in a format suitable for both models.
"""

le=LabelEncoder()
y_label=le.fit_transform(y_label) #encoding y_label from sting literal to integer

# we will use column transformer to encode any columns with dtype 'string',and scale all columns

preprocess=ColumnTransformer([
    ('encoder',OneHotEncoder(),x_label.select_dtypes(exclude=np.number).columns),
    ('scaler',StandardScaler(),x_label.select_dtypes(include=np.number).columns)
],remainder='passthrough',verbose_feature_names_out=False)

x_label=preprocess.fit_transform(x_label)

"""With the features encoded and scaled, we now split the dataset into training and validation sets."""

x_train,x_test,y_train,y_test=train_test_split(x_label,y_label,train_size=0.8)

print(x_label.shape)

"""### Model: Dense Neural Network

Our architecture consists of three hidden Dense layers, each followed by Batch Normalization, which normalizes layer inputs and reduces the need for extensive feature scaling upstream. Hidden layers use the `relu` activation function, while the output layer uses `softmax` to produce a probability distribution over the attack classes. A `Dropout` layer is included before the output layer to reduce overfitting.
"""

model=keras.Sequential([
    layers.Dense(256,activation='relu'),
    layers.BatchNormalization(),
    layers.Dense(128,activation='relu'),
    layers.BatchNormalization(),
    layers.Dense(64,activation='relu'),
    layers.BatchNormalization(),
    layers.Dense(32,activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(len(pd.unique(y_label)),activation="softmax")
])

model.compile(
    optimizer=keras.optimizers.Nadam(learning_rate=0.001),
    loss="sparse_categorical_crossentropy",
    metrics=['accuracy']
)

h=model.fit(x_train,y_train,validation_data=(x_test,y_test),batch_size=32,epochs=8)

"""### Evaluation

The model converged rapidly, reaching approximately 99% training accuracy and 99% validation accuracy within just 3 epochs, with a loss below 0.04. These results indicate strong generalization with minimal overfitting and place the model's performance above typical industry benchmarks for this type of classification task.

---

### Model: Random Forest Classifier

As an alternative to the neural network, we train a Random Forest Classifier. To identify a strong set of hyperparameters, we use `RandomizedSearchCV` to sample from a defined parameter distribution and evaluate candidate models via cross-validation.
"""

Randomfc=Pipeline([
    ('Model',RandomForestClassifier())
])

param_dict={
    "Model__n_estimators": randint(100, 1000),
    "Model__max_depth": [None] + list(range(5, 51, 5)),
    "Model__min_samples_split": randint(2, 20),
    "Model__min_samples_leaf": randint(1, 10),
    "Model__max_features": ["sqrt", "log2", None],
    "Model__criterion": ["gini", "entropy", "log_loss"],
    "Model__class_weight": [None, "balanced", "balanced_subsample"],
    "Model__max_leaf_nodes": [None] + list(range(10, 101, 10)),
}

Rand_search=RandomizedSearchCV(
    Randomfc,
    param_dict,
    cv=2,
    n_iter=5,
    n_jobs=5,
    random_state=32,
    verbose=2,
    scoring='accuracy'
)

Rand_search.fit(x_train[:50000],y_train[:50000])

"""#### Search Results

With the randomized search complete, we inspect the best cross-validated accuracy score achieved across the sampled hyperparameter combinations.
"""

Rand_search.best_score_

"""#### Final Model and Prediction

We extract the best-performing estimator from the search and use it to generate predictions on the held-out validation set.
"""

modele=Rand_search.best_estimator_
modele=modele.named_steps['Model']

pred=modele.predict(x_test)

"""### Evaluation

Finally, we evaluate the Random Forest model's performance by computing its accuracy on the validation set.
"""

score=accuracy_score(y_test,pred)

score

